<?php

use Cubitworx\Laravel\Countries\Model;
use Illuminate\Database\Migrations\Migration;

class SeedCountriesTable extends Migration {

	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up() {
		DB::table('countries')->truncate();

		Model\Country::insert([
			['iso_3166_1'=>'AD', 'name'=>'Andorra', 'nationality' => 'Andorian', 'active'=>0],
			['iso_3166_1'=>'AE', 'name'=>'United Arab Emirates', 'nationality' => 'Emirian', 'active'=>0],
			['iso_3166_1'=>'AF', 'name'=>'Afghanistan', 'nationality' => 'Afghani', 'active'=>0],
			['iso_3166_1'=>'AG', 'name'=>'Antigua and Barbuda', 'nationality' => 'Antiguans', 'active'=>0],
			['iso_3166_1'=>'AI', 'name'=>'Anguilla', 'nationality' => 'Anguillan', 'active'=>0],
			['iso_3166_1'=>'AL', 'name'=>'Albania', 'nationality' => 'Albanian', 'active'=>0],
			['iso_3166_1'=>'AM', 'name'=>'Armenia', 'nationality' => 'Armenian', 'active'=>0],
			['iso_3166_1'=>'AN', 'name'=>'Netherlands Antilles', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'AO', 'name'=>'Angola', 'nationality' => 'Angolan', 'active'=>0],
			['iso_3166_1'=>'AQ', 'name'=>'Antarctica', 'nationality' => 'Antarctic', 'active'=>0],
			['iso_3166_1'=>'AR', 'name'=>'Argentina', 'nationality' => 'Argentine', 'active'=>0],
			['iso_3166_1'=>'AS', 'name'=>'American Samoa', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'AT', 'name'=>'Austria', 'nationality' => 'Austrian', 'active'=>0],
			['iso_3166_1'=>'AU', 'name'=>'Australia', 'nationality' => 'Australian', 'active'=>0],
			['iso_3166_1'=>'AW', 'name'=>'Aruba', 'nationality' => 'Arubian', 'active'=>0],
			['iso_3166_1'=>'AX', 'name'=>'Aland Islands', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'AZ', 'name'=>'Azerbaijan', 'nationality' => 'Azerbaijani', 'active'=>0],
			['iso_3166_1'=>'BA', 'name'=>'Bosnia and Herzegovina', 'nationality' => 'Bosnian', 'active'=>0],
			['iso_3166_1'=>'BB', 'name'=>'Barbados', 'nationality' => 'Barbadian', 'active'=>0],
			['iso_3166_1'=>'BD', 'name'=>'Bangladesh', 'nationality' => 'Bangladeshi', 'active'=>0],
			['iso_3166_1'=>'BE', 'name'=>'Belgium', 'nationality' => 'Belgian', 'active'=>0],
			['iso_3166_1'=>'BF', 'name'=>'Burkina Faso', 'nationality' => 'Burkinabe', 'active'=>0],
			['iso_3166_1'=>'BG', 'name'=>'Bulgaria', 'nationality' => 'Bulgarian', 'active'=>0],
			['iso_3166_1'=>'BH', 'name'=>'Bahrain', 'nationality' => 'Bahrainian', 'active'=>0],
			['iso_3166_1'=>'BI', 'name'=>'Burundi', 'nationality' => 'Burundian', 'active'=>0],
			['iso_3166_1'=>'BJ', 'name'=>'Benin', 'nationality' => 'Beninese', 'active'=>0],
			['iso_3166_1'=>'BL', 'name'=>'Saint Barthélemy', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'BM', 'name'=>'Bermuda', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'BN', 'name'=>'Brunei', 'nationality' => 'Bruneian', 'active'=>0],
			['iso_3166_1'=>'BO', 'name'=>'Bolivia', 'nationality' => 'Bolivian', 'active'=>0],
			['iso_3166_1'=>'BQ', 'name'=>'Bonaire, Saint Eustatius and Saba', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'BR', 'name'=>'Brazil', 'nationality' => 'Brazilian', 'active'=>0],
			['iso_3166_1'=>'BS', 'name'=>'Bahamas', 'nationality' => 'Bahameese', 'active'=>0],
			['iso_3166_1'=>'BT', 'name'=>'Bhutan', 'nationality' => 'Bhutanese', 'active'=>0],
			['iso_3166_1'=>'BV', 'name'=>'Bouvet Island', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'BW', 'name'=>'Botswana', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'BY', 'name'=>'Belarus', 'nationality' => 'Belarusian', 'active'=>0],
			['iso_3166_1'=>'BZ', 'name'=>'Belize', 'nationality' => 'Belizean', 'active'=>0],
			['iso_3166_1'=>'CA', 'name'=>'Canada', 'nationality' => 'Canadian', 'active'=>0],
			['iso_3166_1'=>'CC', 'name'=>'Cocos Islands', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'CD', 'name'=>'Democratic Republic of the Congo', 'nationality' => 'Congolese', 'active'=>0],
			['iso_3166_1'=>'CF', 'name'=>'Central African Republic', 'nationality' => 'Central African', 'active'=>0],
			['iso_3166_1'=>'CG', 'name'=>'Republic of the Congo', 'nationality' => 'Congolese', 'active'=>0],
			['iso_3166_1'=>'CH', 'name'=>'Switzerland', 'nationality' => 'Swiss', 'active'=>0],
			['iso_3166_1'=>'CI', 'name'=>'Ivory Coast', 'nationality' => 'Ivorian', 'active'=>0],
			['iso_3166_1'=>'CK', 'name'=>'Cook Islands', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'CL', 'name'=>'Chile', 'nationality' => 'Chilean', 'active'=>0],
			['iso_3166_1'=>'CM', 'name'=>'Cameroon', 'nationality' => 'Cameroonian', 'active'=>0],
			['iso_3166_1'=>'CN', 'name'=>'China', 'nationality' => 'Chinese', 'active'=>0],
			['iso_3166_1'=>'CO', 'name'=>'Colombia', 'nationality' => 'Colombian', 'active'=>0],
			['iso_3166_1'=>'CR', 'name'=>'Costa Rica', 'nationality' => 'Costa Rican', 'active'=>0],
			['iso_3166_1'=>'CS', 'name'=>'Serbia and Montenegro', 'nationality' => 'Serbian', 'active'=>0],
			['iso_3166_1'=>'CU', 'name'=>'Cuba', 'nationality' => 'Cuban', 'active'=>0],
			['iso_3166_1'=>'CV', 'name'=>'Cape Verde', 'nationality' => 'Cape Verdean', 'active'=>0],
			['iso_3166_1'=>'CW', 'name'=>'Curaçao', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'CX', 'name'=>'Christmas Island', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'CY', 'name'=>'Cyprus', 'nationality' => 'Cypriot', 'active'=>0],
			['iso_3166_1'=>'CZ', 'name'=>'Czech Republic', 'nationality' => 'Czech', 'active'=>0],
			['iso_3166_1'=>'DE', 'name'=>'Germany', 'nationality' => 'German', 'active'=>0],
			['iso_3166_1'=>'DJ', 'name'=>'Djibouti', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'DK', 'name'=>'Denmark', 'nationality' => 'Danish', 'active'=>0],
			['iso_3166_1'=>'DM', 'name'=>'Dominica', 'nationality' => 'Dominican', 'active'=>0],
			['iso_3166_1'=>'DO', 'name'=>'Dominican Republic', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'DZ', 'name'=>'Algeria', 'nationality' => 'Algerian', 'active'=>0],
			['iso_3166_1'=>'EC', 'name'=>'Ecuador', 'nationality' => 'Ecuadorean', 'active'=>0],
			['iso_3166_1'=>'EE', 'name'=>'Estonia', 'nationality' => 'Estonian', 'active'=>0],
			['iso_3166_1'=>'EG', 'name'=>'Egypt', 'nationality' => 'Egyptian', 'active'=>0],
			['iso_3166_1'=>'EH', 'name'=>'Western Sahara', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'ER', 'name'=>'Eritrea', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'ES', 'name'=>'Spain', 'nationality' => 'Spanish', 'active'=>0],
			['iso_3166_1'=>'ET', 'name'=>'Ethiopia', 'nationality' => 'Ethiopian', 'active'=>0],
			['iso_3166_1'=>'FI', 'name'=>'Finland', 'nationality' => 'Finnish', 'active'=>0],
			['iso_3166_1'=>'FJ', 'name'=>'Fiji', 'nationality' => 'Fijian', 'active'=>0],
			['iso_3166_1'=>'FK', 'name'=>'Falkland Islands', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'FM', 'name'=>'Micronesia', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'FO', 'name'=>'Faroe Islands', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'FR', 'name'=>'France', 'nationality' => 'French', 'active'=>0],
			['iso_3166_1'=>'GA', 'name'=>'Gabon', 'nationality' => 'Gabonese', 'active'=>0],
			['iso_3166_1'=>'GB', 'name'=>'United Kingdom', 'nationality' => 'British', 'active'=>0],
			['iso_3166_1'=>'GD', 'name'=>'Grenada', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'GE', 'name'=>'Georgia', 'nationality' => 'Georgian', 'active'=>0],
			['iso_3166_1'=>'GF', 'name'=>'French Guiana', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'GG', 'name'=>'Guernsey', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'GH', 'name'=>'Ghana', 'nationality' => 'Ghanaian', 'active'=>0],
			['iso_3166_1'=>'GI', 'name'=>'Gibraltar', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'GL', 'name'=>'Greenland', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'GM', 'name'=>'Gambia', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'GN', 'name'=>'Guinea', 'nationality' => 'Guinean', 'active'=>0],
			['iso_3166_1'=>'GP', 'name'=>'Guadeloupe', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'GQ', 'name'=>'Equatorial Guinea', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'GR', 'name'=>'Greece', 'nationality' => 'Greek', 'active'=>0],
			['iso_3166_1'=>'GS', 'name'=>'South Georgia and the South Sandwich Islands', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'GT', 'name'=>'Guatemala', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'GU', 'name'=>'Guam', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'GW', 'name'=>'Guinea-Bissau', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'GY', 'name'=>'Guyana', 'nationality' => 'Guyanese', 'active'=>0],
			['iso_3166_1'=>'HK', 'name'=>'Hong Kong', 'nationality' => 'Hongkonger', 'active'=>0],
			['iso_3166_1'=>'HM', 'name'=>'Heard Island and McDonald Islands', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'HN', 'name'=>'Honduras', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'HR', 'name'=>'Croatia', 'nationality' => 'Croatian', 'active'=>0],
			['iso_3166_1'=>'HT', 'name'=>'Haiti', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'HU', 'name'=>'Hungary', 'nationality' => 'Hungarian', 'active'=>0],
			['iso_3166_1'=>'ID', 'name'=>'Indonesia', 'nationality' => 'Indonesian', 'active'=>0],
			['iso_3166_1'=>'IE', 'name'=>'Ireland', 'nationality' => 'Irish', 'active'=>0],
			['iso_3166_1'=>'IL', 'name'=>'Israel', 'nationality' => 'Israeli', 'active'=>0],
			['iso_3166_1'=>'IM', 'name'=>'Isle of Man', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'IN', 'name'=>'India', 'nationality' => 'Indian', 'active'=>0],
			['iso_3166_1'=>'IO', 'name'=>'British Indian Ocean Territory', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'IQ', 'name'=>'Iraq', 'nationality' => 'Iraqi', 'active'=>0],
			['iso_3166_1'=>'IR', 'name'=>'Iran', 'nationality' => 'Iranian', 'active'=>0],
			['iso_3166_1'=>'IS', 'name'=>'Iceland', 'nationality' => 'Icelander', 'active'=>0],
			['iso_3166_1'=>'IT', 'name'=>'Italy', 'nationality' => 'Italian', 'active'=>0],
			['iso_3166_1'=>'JE', 'name'=>'Jersey', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'JM', 'name'=>'Jamaica', 'nationality' => 'Jamaican', 'active'=>0],
			['iso_3166_1'=>'JO', 'name'=>'Jordan', 'nationality' => 'Jordanian', 'active'=>0],
			['iso_3166_1'=>'JP', 'name'=>'Japan', 'nationality' => 'Japanese', 'active'=>0],
			['iso_3166_1'=>'KE', 'name'=>'Kenya', 'nationality' => 'Kenyan', 'active'=>0],
			['iso_3166_1'=>'KG', 'name'=>'Kyrgyzstan', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'KH', 'name'=>'Cambodia', 'nationality' => 'Cambodian', 'active'=>0],
			['iso_3166_1'=>'KI', 'name'=>'Kiribati', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'KM', 'name'=>'Comoros', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'KN', 'name'=>'Saint Kitts and Nevis', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'KP', 'name'=>'North Korea', 'nationality' => 'North Korean', 'active'=>0],
			['iso_3166_1'=>'KR', 'name'=>'South Korea', 'nationality' => 'South Korean', 'active'=>0],
			['iso_3166_1'=>'KW', 'name'=>'Kuwait', 'nationality' => 'Kuwaiti', 'active'=>0],
			['iso_3166_1'=>'KY', 'name'=>'Cayman Islands', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'KZ', 'name'=>'Kazakhstan', 'nationality' => 'Kazakhstani', 'active'=>0],
			['iso_3166_1'=>'LA', 'name'=>'Laos', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'LB', 'name'=>'Lebanon', 'nationality' => 'Lebanese', 'active'=>0],
			['iso_3166_1'=>'LC', 'name'=>'Saint Lucia', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'LI', 'name'=>'Liechtenstein', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'LK', 'name'=>'Sri Lanka', 'nationality' => 'Sri Lankan', 'active'=>0],
			['iso_3166_1'=>'LR', 'name'=>'Liberia', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'LS', 'name'=>'Lesotho', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'LT', 'name'=>'Lithuania', 'nationality' => 'Lithuanian', 'active'=>0],
			['iso_3166_1'=>'LU', 'name'=>'Luxembourg', 'nationality' => 'Luxembourger', 'active'=>0],
			['iso_3166_1'=>'LV', 'name'=>'Latvia', 'nationality' => 'Latvian', 'active'=>0],
			['iso_3166_1'=>'LY', 'name'=>'Libya', 'nationality' => 'Libyan', 'active'=>0],
			['iso_3166_1'=>'MA', 'name'=>'Morocco', 'nationality' => 'Moroccan', 'active'=>0],
			['iso_3166_1'=>'MC', 'name'=>'Monaco', 'nationality' => 'Monacan', 'active'=>0],
			['iso_3166_1'=>'MD', 'name'=>'Moldova', 'nationality' => 'Moldovan', 'active'=>0],
			['iso_3166_1'=>'ME', 'name'=>'Montenegro', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'MF', 'name'=>'Saint Martin', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'MG', 'name'=>'Madagascar', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'MH', 'name'=>'Marshall Islands', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'MK', 'name'=>'Macedonia', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'ML', 'name'=>'Mali', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'MM', 'name'=>'Myanmar', 'nationality' => 'Mayanmarese', 'active'=>0],
			['iso_3166_1'=>'MN', 'name'=>'Mongolia', 'nationality' => 'Mongolian', 'active'=>0],
			['iso_3166_1'=>'MO', 'name'=>'Macao', 'nationality' => 'Macau', 'active'=>0],
			['iso_3166_1'=>'MP', 'name'=>'Northern Mariana Islands', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'MQ', 'name'=>'Martinique', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'MR', 'name'=>'Mauritania', 'nationality' => 'Mauritanian', 'active'=>0],
			['iso_3166_1'=>'MS', 'name'=>'Montserrat', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'MT', 'name'=>'Malta', 'nationality' => 'Maltese', 'active'=>0],
			['iso_3166_1'=>'MU', 'name'=>'Mauritius', 'nationality' => 'Mauritian', 'active'=>0],
			['iso_3166_1'=>'MV', 'name'=>'Maldives', 'nationality' => 'Maldivian', 'active'=>0],
			['iso_3166_1'=>'MW', 'name'=>'Malawi', 'nationality' => 'Malawian', 'active'=>0],
			['iso_3166_1'=>'MX', 'name'=>'Mexico', 'nationality' => 'Mexican', 'active'=>0],
			['iso_3166_1'=>'MY', 'name'=>'Malaysia', 'nationality' => 'Malaysian', 'active'=>0],
			['iso_3166_1'=>'MZ', 'name'=>'Mozambique', 'nationality' => 'Mozambican', 'active'=>0],
			['iso_3166_1'=>'NA', 'name'=>'Namibia', 'nationality' => 'Namibian', 'active'=>0],
			['iso_3166_1'=>'NC', 'name'=>'New Caledonia', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'NE', 'name'=>'Niger', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'NF', 'name'=>'Norfolk Island', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'NG', 'name'=>'Nigeria', 'nationality' => 'Nigerian', 'active'=>0],
			['iso_3166_1'=>'NI', 'name'=>'Nicaragua', 'nationality' => 'Nicaraguan', 'active'=>0],
			['iso_3166_1'=>'NL', 'name'=>'Netherlands', 'nationality' => 'Dutch', 'active'=>0],
			['iso_3166_1'=>'NO', 'name'=>'Norway', 'nationality' => 'Norwegian', 'active'=>0],
			['iso_3166_1'=>'NP', 'name'=>'Nepal', 'nationality' => 'Nepalese', 'active'=>0],
			['iso_3166_1'=>'NR', 'name'=>'Nauru', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'NU', 'name'=>'Niue', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'NZ', 'name'=>'New Zealand', 'nationality' => 'New Zealander', 'active'=>0],
			['iso_3166_1'=>'OM', 'name'=>'Oman', 'nationality' => 'Omani', 'active'=>0],
			['iso_3166_1'=>'PA', 'name'=>'Panama', 'nationality' => 'Panamanian', 'active'=>0],
			['iso_3166_1'=>'PE', 'name'=>'Peru', 'nationality' => 'Peruvian', 'active'=>0],
			['iso_3166_1'=>'PF', 'name'=>'French Polynesia', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'PG', 'name'=>'Papua New Guinea', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'PH', 'name'=>'Philippines', 'nationality' => 'Filipino', 'active'=>0],
			['iso_3166_1'=>'PK', 'name'=>'Pakistan', 'nationality' => 'Pakistani', 'active'=>0],
			['iso_3166_1'=>'PL', 'name'=>'Poland', 'nationality' => 'Polish', 'active'=>0],
			['iso_3166_1'=>'PM', 'name'=>'Saint Pierre and Miquelon', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'PN', 'name'=>'Pitcairn', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'PR', 'name'=>'Puerto Rico', 'nationality' => 'Puerto Rican', 'active'=>0],
			['iso_3166_1'=>'PS', 'name'=>'Palestinian Territory', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'PT', 'name'=>'Portugal', 'nationality' => 'Portugees', 'active'=>0],
			['iso_3166_1'=>'PW', 'name'=>'Palau', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'PY', 'name'=>'Paraguay', 'nationality' => 'Paraguayan', 'active'=>0],
			['iso_3166_1'=>'QA', 'name'=>'Qatar', 'nationality' => 'Qatari', 'active'=>0],
			['iso_3166_1'=>'RE', 'name'=>'Reunion', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'RO', 'name'=>'Romania', 'nationality' => 'Romanian', 'active'=>0],
			['iso_3166_1'=>'RS', 'name'=>'Serbia', 'nationality' => 'Serbian', 'active'=>0],
			['iso_3166_1'=>'RU', 'name'=>'Russia', 'nationality' => 'Russian', 'active'=>0],
			['iso_3166_1'=>'RW', 'name'=>'Rwanda', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'SA', 'name'=>'Saudi Arabia', 'nationality' => 'Saudi Arabian', 'active'=>0],
			['iso_3166_1'=>'SB', 'name'=>'Solomon Islands', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'SC', 'name'=>'Seychelles', 'nationality' => 'Seychellois Creole', 'active'=>0],
			['iso_3166_1'=>'SD', 'name'=>'Sudan', 'nationality' => 'Sudanese', 'active'=>0],
			['iso_3166_1'=>'SE', 'name'=>'Sweden', 'nationality' => 'Swedish', 'active'=>0],
			['iso_3166_1'=>'SG', 'name'=>'Singapore', 'nationality' => 'Singaporean', 'active'=>0],
			['iso_3166_1'=>'SH', 'name'=>'Saint Helena', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'SI', 'name'=>'Slovenia', 'nationality' => 'Slovenian', 'active'=>0],
			['iso_3166_1'=>'SJ', 'name'=>'Svalbard and Jan Mayen', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'SK', 'name'=>'Slovakia', 'nationality' => 'Slovakian', 'active'=>0],
			['iso_3166_1'=>'SL', 'name'=>'Sierra Leone', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'SM', 'name'=>'San Marino', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'SN', 'name'=>'Senegal', 'nationality' => 'Senegalese', 'active'=>0],
			['iso_3166_1'=>'SO', 'name'=>'Somalia', 'nationality' => 'Somali', 'active'=>0],
			['iso_3166_1'=>'SR', 'name'=>'Suriname', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'SS', 'name'=>'South Sudan', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'ST', 'name'=>'Sao Tome and Principe', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'SV', 'name'=>'El Salvador', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'SX', 'name'=>'Sint Maarten', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'SY', 'name'=>'Syria', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'SZ', 'name'=>'Swaziland', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'TC', 'name'=>'Turks and Caicos Islands', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'TD', 'name'=>'Chad', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'TF', 'name'=>'French Southern Territories', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'TG', 'name'=>'Togo', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'TH', 'name'=>'Thailand', 'nationality' => 'Thai', 'active'=>0],
			['iso_3166_1'=>'TJ', 'name'=>'Tajikistan', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'TK', 'name'=>'Tokelau', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'TL', 'name'=>'East Timor', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'TM', 'name'=>'Turkmenistan', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'TN', 'name'=>'Tunisia', 'nationality' => 'Tunisian', 'active'=>0],
			['iso_3166_1'=>'TO', 'name'=>'Tonga', 'nationality' => 'Tongan', 'active'=>0],
			['iso_3166_1'=>'TR', 'name'=>'Turkey', 'nationality' => 'Turkish', 'active'=>0],
			['iso_3166_1'=>'TT', 'name'=>'Trinidad and Tobago', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'TV', 'name'=>'Tuvalu', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'TW', 'name'=>'Taiwan', 'nationality' => 'Taiwanese', 'active'=>0],
			['iso_3166_1'=>'TZ', 'name'=>'Tanzania', 'nationality' => 'Tanzanian', 'active'=>0],
			['iso_3166_1'=>'UA', 'name'=>'Ukraine', 'nationality' => 'Ukrainian', 'active'=>0],
			['iso_3166_1'=>'UG', 'name'=>'Uganda', 'nationality' => 'Ugandan', 'active'=>0],
			['iso_3166_1'=>'UM', 'name'=>'United States Minor Outlying Islands', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'US', 'name'=>'United States', 'nationality' => 'American', 'active'=>0],
			['iso_3166_1'=>'UY', 'name'=>'Uruguay', 'nationality' => 'Uruguayan', 'active'=>0],
			['iso_3166_1'=>'UZ', 'name'=>'Uzbekistan', 'nationality' => 'Uzbekistani', 'active'=>0],
			['iso_3166_1'=>'VA', 'name'=>'Vatican', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'VC', 'name'=>'Saint Vincent and the Grenadines', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'VE', 'name'=>'Venezuela', 'nationality' => 'Venezuelan', 'active'=>0],
			['iso_3166_1'=>'VG', 'name'=>'British Virgin Islands', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'VI', 'name'=>'U.S. Virgin Islands', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'VN', 'name'=>'Vietnam', 'nationality' => 'Vietnamese', 'active'=>0],
			['iso_3166_1'=>'VU', 'name'=>'Vanuatu', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'WF', 'name'=>'Wallis and Futuna', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'WS', 'name'=>'Samoa', 'nationality' => 'Samoan', 'active'=>0],
			['iso_3166_1'=>'XK', 'name'=>'Kosovo', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'YE', 'name'=>'Yemen', 'nationality' => 'Yemeni', 'active'=>0],
			['iso_3166_1'=>'YT', 'name'=>'Mayotte', 'nationality' => null, 'active'=>0],
			['iso_3166_1'=>'ZA', 'name'=>'South Africa', 'nationality' => 'South African', 'active'=>0],
			['iso_3166_1'=>'ZM', 'name'=>'Zambia', 'nationality' => 'Zambian', 'active'=>0],
			['iso_3166_1'=>'ZW', 'name'=>'Zimbabwe', 'nationality' => 'Zimbabwean', 'active'=>0],
		]);
	}

	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down() {
		DB::table('countries')->truncate();
	}

}
